title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-cayman

conference_name: "GUI Agents with Foundation Models: Data Resource, Framework and Application"
conference_location: "Tutorial @ IJCAI 2025"
# conference_intro: "Will be held in 2025"
conference_intro: ""

collections:
  organizers:
    output: true
  speakers:
    output: true
